AP-24030: Provoke test failure
This provokes a test that fails sporadically on Jenkins like this:
Run Tycho Maven Build / testExceptionHandlingOnWrite –
org.knime.core.columnar.cache.data.ReadDataCacheTest
Error
expected:<1> but was:<2>
Stacktrace
java.lang.AssertionError: expected:<1> but was:<2>
    at org.junit.Assert.fail(Assert.java:89)
    at org.junit.Assert.failNotEquals(Assert.java:835)
    at org.junit.Assert.assertEquals(Assert.java:647)
    at org.junit.Assert.assertEquals(Assert.java:633)
    at
org.knime.core.columnar.TestBatchStoreUtils.checkRefs(TestBatchStoreUtils.java:473)
    at
org.knime.core.columnar.cache.data.ReadDataCacheTest.testExceptionHandlingOnWrite(ReadDataCacheTest.java:513)

The reason that this often does not show up is that the store is often
closed before any batch-writing future has actually started running.
Then the exception that is supposed to be thrown is never thrown and
everything works fine. (The write jobs check whether m_closed is set and
then don't do any actual writing.)

Attempting a store.flush() before store.close() will start writing the
first batch, which triggers the exception, and the subsequent test
failure.